window.ANC_STORE = {
  brand: 'ANC Tools',
  company: 'Aseem and Consulting Pvt Ltd',
  whatsapp: '9779802840041',
  phone: '+977 9802840041',
  email: 'info@anc.com.np',
  address: 'Kushma 05 Parbat, Kushma, Gandaki 33400, Nepal',
  site: 'https://tools.anc.com.np/',
  mainSite: 'https://anc.com.np/',
  plans: ['1 month', '3 months', '12 months'],
  hours: 'Usually replies within a few minutes during Nepal daytime.',

  categories: [
    { slug: 'ai-tools', name: 'AI Tools', nav: 'AI', icon: 'spark', blurb: 'Chat, image, video, and coding assistants.' },
    { slug: 'academic', name: 'Academic Tools', nav: 'Academic', icon: 'book', blurb: 'Writing, citations, and originality checks for study and papers.' },
    { slug: 'microsoft', name: 'Microsoft', nav: 'Microsoft', icon: 'win', blurb: 'Windows, Office, Visio, Project, and Microsoft 365.' },
    { slug: 'graphics', name: 'Design & Video', nav: 'Design', icon: 'pen', blurb: 'Canva, Adobe, Figma, AutoCAD, and video editors.' },
    { slug: 'cloud', name: 'Cloud', nav: 'Cloud', icon: 'cloud', blurb: 'Email, storage, meetings, hosting, and virtual machines.' },
    { slug: 'antivirus', name: 'Antivirus', nav: 'Antivirus', icon: 'shield', blurb: 'Device and identity protection suites.' },
    { slug: 'vpn', name: 'VPN', nav: 'VPN', icon: 'lock', blurb: 'Private connections for travel, Wi-Fi, and streaming.' },
    { slug: 'learning', name: 'Learning', nav: 'Learning', icon: 'grad', blurb: 'Courses, languages, and student packs.' },
    { slug: 'streaming', name: 'Streaming', nav: 'Streaming', icon: 'play', blurb: 'Films, series, music, and anime.' },
    { slug: 'productivity', name: 'Work tools', nav: 'Work', icon: 'brief', blurb: 'PDF, passwords, recovery, and everyday office apps.' }
  ],

  heroes: ['chatgpt-plus', 'adobe-creative-cloud', 'cursor-ai'],

  products: [
    { slug: 'titan-mail', name: 'Titan Mail', category: 'cloud', color: '#1a73e8', blurb: 'Business email on your domain with spam protection and calendar.' },
    { slug: 'google-meet', name: 'Google Meet', category: 'cloud', color: '#00832d', blurb: 'HD video meetings with recording and larger participant limits.' },
    { slug: 'microsoft-onedrive', name: 'Microsoft OneDrive', category: 'cloud', color: '#0078d4', blurb: 'Cloud storage that syncs files across Windows, Mac, and mobile.' },
    { slug: 'google-one', name: 'Google One', category: 'cloud', color: '#4285f4', blurb: 'Extra Google storage for Drive, Gmail, and Photos.' },
    { slug: 'zoom-pro', name: 'Zoom Pro', category: 'cloud', color: '#2d8cff', blurb: 'Longer meetings, cloud recording, and host controls for teams.' },

    { slug: 'stealth-writer', name: 'Stealth Writer', category: 'ai-tools', color: '#7c3aed', recently: true, blurb: 'AI writing assistant for long-form drafts and rewrites.' },
    { slug: 'hix-ai-bypass', name: 'HIX AI Bypass', category: 'ai-tools', color: '#111827', deal: true, heroTag: 'Humanize AI drafts', blurb: 'Rewrite AI text so it reads more naturally for academic and work use.' },
    { slug: 'chatgpt-plus', name: 'ChatGPT Plus', category: 'ai-tools', color: '#10a37f', heroTag: 'GPT models, images, and custom GPTs', blurb: 'Priority access to GPT models, image generation, and custom GPTs.' },
    { slug: 'google-gemini-ai', name: 'Google Gemini AI', category: 'ai-tools', color: '#4285f4', deal: true, blurb: 'Google’s multimodal AI for writing, research, and image prompts.' },

    { slug: 'paperpal-premium', name: 'Paperpal Premium', category: 'academic', color: '#2563eb', recently: true, heroTag: 'Academic writing tool', blurb: 'Academic English editing, paraphrasing, and submission checks.' },
    { slug: 'jenni-ai', name: 'Jenni AI', category: 'academic', color: '#0f766e', blurb: 'Research writing assistant with citations and outline help.' },
    { slug: 'ai-plagiarism-checker', name: 'AI & Plagiarism Checker', category: 'academic', color: '#dc2626', hidden: true, blurb: 'Scan drafts for similarity and AI-generated phrasing before you submit.' },
    { slug: 'scribd-premium', name: 'Scribd Premium', category: 'academic', color: '#1e3a5f', recently: true, blurb: 'Books, audiobooks, magazines, and documents in one library.' },
    { slug: 'quillbot-premium', name: 'Quillbot Premium', category: 'academic', color: '#499557', blurb: 'Paraphrase, grammar, and citation tools for faster editing.' },
    { slug: 'grammarly', name: 'Grammarly', category: 'academic', color: '#15c39a', blurb: 'Grammar, tone, and clarity suggestions across the browser and docs.' },

    { slug: 'visio-professional', name: 'Visio Professional', category: 'microsoft', color: '#3955a3', blurb: 'Diagrams, flowcharts, and network maps for Windows.' },
    { slug: 'windows-11-pro', name: 'Windows 11 Pro', category: 'microsoft', color: '#0078d4', blurb: 'Genuine Windows 11 Pro license for a single PC.' },
    { slug: 'microsoft-365-personal', name: 'Microsoft 365 Personal', category: 'microsoft', color: '#d83b01', blurb: 'Word, Excel, PowerPoint, Outlook, and OneDrive for one person.' },
    { slug: 'windows-server', name: 'Windows Server', category: 'microsoft', color: '#00188f', blurb: 'Windows Server license for lab, office, or hosting use.' },
    { slug: 'microsoft-365-family', name: 'Microsoft 365 Family', category: 'microsoft', color: '#d83b01', blurb: 'Office apps and cloud storage for up to six people.' },
    { slug: 'office-windows', name: 'Office for Windows PC', category: 'microsoft', color: '#ea3e23', blurb: 'Classic Office suite license for a Windows computer.' },
    { slug: 'office-mac', name: 'Office for Mac', category: 'microsoft', color: '#ea3e23', blurb: 'Word, Excel, and PowerPoint for Mac.' },
    { slug: 'project-professional', name: 'Project Professional', category: 'microsoft', color: '#31752f', blurb: 'Schedules, Gantt charts, and resource planning.' },
    { slug: 'office-365-account', name: 'Office 365 Account', category: 'microsoft', color: '#d83b01', blurb: 'Microsoft 365 account setup for web and desktop apps.' },

    { slug: 'clipchamp', name: 'Microsoft Clipchamp', category: 'graphics', color: '#0078d4', blurb: 'Browser video editor with stock media and auto captions.' },
    { slug: 'coreldraw', name: 'CorelDRAW Software', category: 'graphics', color: '#24b06d', blurb: 'Vector illustration and layout for print and brand work.' },
    { slug: 'canva-pro-edu', name: 'Canva Pro Edu', category: 'graphics', color: '#00c4cc', blurb: 'Canva Pro features for students and educators.' },
    { slug: 'canva-professional', name: 'Canva Professional', category: 'graphics', color: '#7d2ae8', deal: true, blurb: 'Brand kits, Magic Studio, and premium templates.' },
    { slug: 'adobe-photography', name: 'Adobe Photography Plan', category: 'graphics', color: '#001e36', blurb: 'Photoshop and Lightroom with cloud photo storage.' },
    { slug: 'capcut-pro', name: 'CapCut Pro', category: 'graphics', color: '#000000', blurb: 'Pro video effects, 4K export, and no watermark.' },
    { slug: 'envato-elements', name: 'Envato Elements', category: 'graphics', color: '#82b441', blurb: 'Unlimited stock video, music, templates, and graphics.' },
    { slug: 'adobe-creative-cloud', name: 'Adobe Creative Cloud', category: 'graphics', color: '#da1f26', heroTag: 'Photoshop, Premiere, and Illustrator', blurb: 'Full Adobe app suite including Premiere, Illustrator, and more.' },

    { slug: 'kaspersky-vpn', name: 'Kaspersky VPN', category: 'vpn', color: '#006d5b', blurb: 'VPN from Kaspersky with split tunneling and kill switch.' },
    { slug: 'surfshark-vpn', name: 'Surfshark VPN', category: 'vpn', color: '#1e5cfc', blurb: 'Unlimited devices, CleanWeb, and servers in 100+ countries.' },
    { slug: 'hma-vpn', name: 'HMA VPN', category: 'vpn', color: '#00b140', blurb: 'HideMyAss VPN for streaming and public Wi-Fi.' },
    { slug: 'nordvpn', name: 'NordVPN', category: 'vpn', color: '#4687ff', deal: true, blurb: 'Fast VPN with Threat Protection and a large server network.' },
    { slug: 'avast-vpn', name: 'Avast SecureLine VPN', category: 'vpn', color: '#ff7800', blurb: 'Simple VPN bundled with Avast security tools.' },
    { slug: 'express-vpn', name: 'ExpressVPN', category: 'vpn', color: '#da3940', recently: true, blurb: 'Reliable VPN with Lightway protocol and easy apps.' },

    { slug: 'nitro-pdf-pro', name: 'Nitro PDF Pro', category: 'productivity', color: '#f36f21', blurb: 'Create, edit, sign, and convert PDFs without Adobe.' },
    { slug: 'notion', name: 'Notion', category: 'productivity', color: '#000000', blurb: 'Notes, wikis, and project databases in one workspace.' },
    { slug: 'cleanmymac-x', name: 'CleanMyMac X', category: 'productivity', color: '#1d6fe9', blurb: 'Mac cleaner, uninstaller, and malware scan.' },
    { slug: 'easeus-data-recovery', name: 'EaseUS Data Recovery Pro', category: 'productivity', color: '#00a0e9', deal: true, blurb: 'Recover deleted files from disks, USBs, and memory cards.' },
    { slug: 'ccleaner-professional', name: 'CCleaner Professional', category: 'productivity', color: '#e21e26', blurb: 'Windows cleanup, startup control, and driver updates.' },
    { slug: 'linkedin-premium', name: 'LinkedIn Premium', category: 'productivity', color: '#0a66c2', recently: true, deal: true, heroTag: 'See who viewed your profile', blurb: 'InMail, applicant insights, and who viewed your profile.' },
    { slug: 'truecaller', name: 'Truecaller', category: 'productivity', color: '#0ea5e9', blurb: 'Caller ID, spam blocking, and verified business listings.' },

    { slug: 'codedex-club', name: 'Codedex Club', category: 'learning', color: '#7c3aed', blurb: 'Learn to code with projects, quests, and a community club.' },
    { slug: 'kids-worksheets', name: '6000+ Kids Printable Worksheets', category: 'learning', color: '#f59e0b', blurb: 'Printable packs for early maths, English, and activities.' },
    { slug: 'datacamp', name: 'DataCamp', category: 'learning', color: '#03ef62', blurb: 'Data science and Python courses with in-browser practice.' },
    { slug: 'educative', name: 'Educative', category: 'learning', color: '#4951f5', blurb: 'Text-based software courses without video fluff.' },
    { slug: 'skillshare', name: 'Skillshare', category: 'learning', color: '#17c5cc', blurb: 'Creative classes in design, video, photography, and business.' },
    { slug: 'linkedin-learning', name: 'LinkedIn Learning', category: 'learning', color: '#0a66c2', blurb: 'Professional courses that can show on your LinkedIn profile.' },
    { slug: 'udemy', name: 'Udemy', category: 'learning', color: '#a435f0', blurb: 'Lifetime access to selected Udemy courses you choose with us.' },

    { slug: 'norton-security', name: 'Norton Security', category: 'antivirus', color: '#fbbf24', blurb: 'Antivirus, VPN, and dark-web monitoring in one suite.' },
    { slug: 'avg-internet-security', name: 'AVG Internet Security', category: 'antivirus', color: '#ff8000', blurb: 'Real-time protection, firewall, and email shield.' },
    { slug: 'eset-antivirus', name: 'ESET Antivirus', category: 'antivirus', color: '#003da5', recently: true, blurb: 'Lightweight antivirus known for low system impact.' },
    { slug: 'bitdefender-antivirus', name: 'Bitdefender Antivirus', category: 'antivirus', color: '#ed1c24', recently: true, blurb: 'Strong malware detection with ransomware remediation.' },
    { slug: 'mcafee-internet-security', name: 'McAfee Internet Security', category: 'antivirus', color: '#c01820', blurb: 'Multi-device McAfee protection for home internet use.' },
    { slug: 'mcafee-total-protection', name: 'McAfee Total Protection', category: 'antivirus', color: '#c01820', blurb: 'Identity, antivirus, and password tools in one plan.' },
    { slug: 'mcafee-antivirus', name: 'McAfee AntiVirus', category: 'antivirus', color: '#c01820', blurb: 'Core McAfee antivirus for a single PC.' },
    { slug: 'kaspersky', name: 'Kaspersky', category: 'antivirus', color: '#006d5b', blurb: 'Kaspersky antivirus and web protection for Windows and Mac.' },

    { slug: 'speechelo-pro', name: 'Speechelo Pro', category: 'ai-tools', color: '#16a34a', blurb: 'Text-to-speech voices for videos and e-learning.' },
    { slug: 'jetbrains-premium', name: 'JetBrains Premium', category: 'productivity', color: '#fe315d', blurb: 'IntelliJ, PyCharm, WebStorm, and other JetBrains IDEs.' },
    { slug: 'dashlane', name: 'Dashlane Password Manager', category: 'productivity', color: '#0e353d', blurb: 'Passwords, autofill, and a VPN in one app.' },
    { slug: '1password', name: '1Password Premium', category: 'productivity', color: '#0572ec', blurb: 'Family or personal password vaults with Watchtower alerts.' },
    { slug: 'roboform', name: 'RoboForm Password Manager', category: 'productivity', color: '#e21e26', blurb: 'Password manager with form filling for long applications.' },
    { slug: 'github-student', name: 'GitHub Student Developer Pack', category: 'learning', color: '#24292f', blurb: 'Help verifying and using GitHub Education student benefits.' },
    { slug: 'idm', name: 'Internet Download Manager (IDM)', category: 'productivity', color: '#0072c6', blurb: 'Faster downloads and resume support for Windows.' },
    { slug: 'autodesk-apps', name: 'Autodesk Apps', category: 'graphics', color: '#0696d7', blurb: 'AutoCAD, Revit, or related Autodesk apps — ask which title you need.' },
    { slug: 'icloud', name: 'iCloud Storage', category: 'cloud', color: '#3693f3', recently: true, blurb: 'Extra iCloud space for photos, backups, and files across Apple devices.' },

    { slug: 'claude-ai', name: 'Claude AI', category: 'ai-tools', color: '#d97757', recently: true, blurb: 'Anthropic’s AI assistant for writing, coding, and long documents.' },
    { slug: 'grok', name: 'Grok', category: 'ai-tools', color: '#000000', recently: true, blurb: 'xAI’s Grok assistant with real-time answers and image generation.' },
    { slug: 'perplexity-ai', name: 'Perplexity AI', category: 'ai-tools', color: '#20808d', blurb: 'AI search with cited answers for research and current topics.' },
    { slug: 'google-ai-ultra', name: 'Google AI Ultra', category: 'ai-tools', color: '#4285f4', blurb: 'Google’s higher-tier AI plan across Gemini and related tools.' },
    { slug: 'midjourney', name: 'Midjourney', category: 'ai-tools', color: '#1a1a2e', blurb: 'AI image generation for concept art, product shots, and mood boards.' },
    { slug: 'elevenlabs', name: 'ElevenLabs', category: 'ai-tools', color: '#000000', blurb: 'Natural AI voices for videos, podcasts, and narration.' },
    { slug: 'replit-core', name: 'Replit Core', category: 'ai-tools', color: '#f26207', blurb: 'Cloud IDE with AI coding, hosting, and collaboration.' },
    { slug: 'lovable-ai', name: 'Lovable AI', category: 'ai-tools', color: '#ec4899', blurb: 'Build web apps from prompts with Lovable’s AI builder.' },
    { slug: 'originality-ai', name: 'Originality AI', category: 'ai-tools', color: '#2563eb', blurb: 'AI and plagiarism detection for publishers and agencies.' },
    { slug: 'semrush', name: 'Semrush', category: 'ai-tools', color: '#ff622d', blurb: 'SEO, keywords, and competitor research in one suite.' },
    { slug: 'descript-ai', name: 'Descript', category: 'ai-tools', color: '#5b4dff', blurb: 'Edit video and podcasts like a doc, with AI voices and studio sound.' },
    { slug: 'gamma-ai', name: 'Gamma', category: 'ai-tools', color: '#8b5cf6', blurb: 'AI decks and docs that look presentation-ready in minutes.' },
    { slug: 'devin-ai', name: 'Devin AI', category: 'ai-tools', color: '#0f172a', blurb: 'AI software engineer for coding tasks you brief in chat.' },
    { slug: 'suno-ai', name: 'Suno AI', category: 'ai-tools', color: '#000000', blurb: 'Generate songs with lyrics, vocals, and instrumentals from a prompt.' },
    { slug: 'bolt-ai', name: 'Bolt', category: 'ai-tools', color: '#136bf5', blurb: 'Ship full-stack apps in the browser from a prompt.' },
    { slug: 'heygen-ai', name: 'HeyGen', category: 'ai-tools', color: '#000000', blurb: 'AI avatars and translated talking videos for marketing and training.' },
    { slug: 'invideo-ai', name: 'InVideo AI', category: 'ai-tools', color: '#7c3aed', blurb: 'Turn scripts into short videos with stock, captions, and AI voice.' },
    { slug: 'pollo-ai', name: 'Pollo AI', category: 'ai-tools', color: '#f59e0b', blurb: 'AI video generator for social clips and product demos.' },

    { slug: 'gptzero', name: 'GPTZero', category: 'academic', color: '#111827', blurb: 'Check whether text looks AI-written before you submit or publish.' },
    { slug: 'turnitin', name: 'Turnitin', category: 'academic', color: '#a51c30', blurb: 'Similarity and originality checks used by schools and journals.' },
    { slug: 'humanizeai-pro', name: 'HumanizeAI Pro', category: 'academic', color: '#0ea5e9', blurb: 'Rewrite AI drafts so they read more like human writing.' },
    { slug: 'humbot-ai', name: 'Humbot AI', category: 'academic', color: '#6366f1', blurb: 'Humanize and detect AI text for essays and reports.' },

    { slug: 'figma', name: 'Figma', category: 'graphics', color: '#f24e1e', recently: true, blurb: 'Collaborative UI design, prototyping, and FigJam boards.' },
    { slug: 'beautiful-ai', name: 'Beautiful.ai', category: 'graphics', color: '#4c6ef5', blurb: 'Smart slide layouts that keep decks on-brand as you type.' },
    { slug: 'freepik-premium', name: 'Freepik Premium', category: 'graphics', color: '#1273eb', blurb: 'Stock photos, vectors, and AI assets without the free-tier limits.' },
    { slug: 'adobe-premiere-pro', name: 'Adobe Premiere Pro', category: 'graphics', color: '#9999ff', blurb: 'Professional video editing for YouTube, film, and client work.' },
    { slug: 'filmora', name: 'Wondershare Filmora', category: 'graphics', color: '#1137ff', blurb: 'Easy video editor with effects, captions, and stock media.' },

    { slug: 'mcafee-mobile-vpn', name: 'McAfee Mobile Security + VPN', category: 'vpn', color: '#c01820', blurb: 'Phone security plus a VPN for public Wi-Fi and travel.' },

    { slug: 'iscanner', name: 'iScanner', category: 'productivity', color: '#2563eb', blurb: 'Scan, sign, and OCR documents from your phone.' },
    { slug: 'wps-office-pro', name: 'WPS Office Pro', category: 'productivity', color: '#c8161d', blurb: 'Word, Excel, and PDF tools as a lighter Office alternative.' },
    { slug: 'cursor-ai', name: 'Cursor', category: 'ai-tools', color: '#000000', recently: true, heroTag: 'AI code editor for Mac and Windows', blurb: 'AI code editor based on VS Code for faster shipping.' },

    { slug: 'coursera-plus', name: 'Coursera Plus', category: 'learning', color: '#0056d2', blurb: 'Unlimited Coursera certificates and courses for a year.' },
    { slug: 'duolingo-super', name: 'Super Duolingo', category: 'learning', color: '#58cc02', blurb: 'Ad-free Duolingo with unlimited hearts and extra practice.' },

    { slug: 'epidemic-sound', name: 'Epidemic Sound', category: 'graphics', color: '#000000', blurb: 'Royalty-free music and SFX for YouTube and client videos.' },

    { slug: 'mcafee-livesafe', name: 'McAfee LiveSafe', category: 'antivirus', color: '#c01820', blurb: 'Unlimited-device McAfee protection for a household.' },

    { slug: 'netflix', name: 'Netflix', category: 'streaming', color: '#e50914', recently: true, deal: true, blurb: 'Stream series and films. Ask which plan and screens you need.' },
    { slug: 'spotify-premium', name: 'Spotify Premium', category: 'streaming', color: '#1db954', recently: true, deal: true, blurb: 'Ad-free music, downloads, and higher quality audio.' },
    { slug: 'youtube-premium', name: 'YouTube Premium', category: 'streaming', color: '#ff0000', recently: true, blurb: 'Ad-free YouTube, background play, and YouTube Music.' },
    { slug: 'prime-video', name: 'Prime Video', category: 'streaming', color: '#00a8e1', blurb: 'Amazon Prime Video for movies and series on your devices.' },
    { slug: 'crunchyroll', name: 'Crunchyroll', category: 'streaming', color: '#f47521', blurb: 'Anime streaming with simulcasts and a large catalog.' },
    { slug: 'sony-liv', name: 'SonyLIV', category: 'streaming', color: '#000000', blurb: 'Sports, shows, and Sony network content for South Asia.' },
    { slug: 'zee5', name: 'ZEE5', category: 'streaming', color: '#6c2bd9', blurb: 'Hindi and regional films, serials, and originals.' },

    { slug: 'google-workspace', name: 'Google Workspace', category: 'cloud', color: '#1a73e8', recently: true, blurb: 'Business Gmail, Drive, Meet, and admin controls on your domain.' },
    { slug: 'google-workspace-education', name: 'Personal Google Workspace Education Plan - 1 Domain, 10 TB Drive, 5 Emails', category: 'cloud', color: '#1a73e8', recently: true, blurb: 'Education Workspace on 1 domain: 10 TB Drive and 5 custom email accounts.' },
    { slug: 'digitalocean', name: 'DigitalOcean', category: 'cloud', color: '#0080ff', blurb: 'Cloud droplets and hosting for sites, APIs, and student labs.' },
    { slug: 'remote-desktop', name: 'Remote Desktop', category: 'cloud', color: '#0078d4', blurb: 'Remote Windows desktop access for work from another PC.' },

    { slug: 'higgsfield', name: 'Higgsfield', category: 'ai-tools', color: '#7c3aed', recently: true, blurb: 'AI video and image generation for social and campaign clips.' },
    { slug: 'kling-ai', name: 'Kling AI', category: 'ai-tools', color: '#111827', blurb: 'Text-to-video generation for ads, storyboards, and shorts.' },
    { slug: 'github-copilot', name: 'GitHub Copilot', category: 'ai-tools', color: '#24292f', recently: true, blurb: 'AI pair programmer in VS Code, JetBrains, and GitHub.' },
    { slug: 'microsoft-copilot', name: 'Microsoft Copilot', category: 'ai-tools', color: '#0078d4', blurb: 'Copilot in Microsoft 365 for Word, Excel, Outlook, and Teams.' },
    { slug: 'writehuman', name: 'WriteHuman', category: 'academic', color: '#0f766e', blurb: 'Humanize AI drafts for essays and blog posts before you submit.' },
    { slug: 'zerogpt', name: 'ZeroGPT', category: 'academic', color: '#111827', blurb: 'Detect AI-written text for schools, editors, and hiring.' },
    { slug: 'german-exam', name: 'German Exam Preparation', category: 'learning', color: '#dd0000', blurb: 'Goethe / TELC-style German exam packs — ask which level you need.' },

    { slug: 'adobe-acrobat', name: 'Adobe Acrobat', category: 'graphics', color: '#ec1c24', blurb: 'Create, edit, sign, and OCR PDFs with Adobe Acrobat.' },
    { slug: 'corel-videostudio', name: 'Corel VideoStudio Ultimate', category: 'graphics', color: '#24b06d', blurb: 'Consumer video editor with effects, screen capture, and discs.' },
    { slug: 'vmware-fusion', name: 'VMware Fusion Pro', category: 'cloud', color: '#607078', blurb: 'Run Windows and Linux VMs on a Mac.' },
    { slug: 'parallels-desktop', name: 'Parallels Desktop', category: 'cloud', color: '#e31c23', blurb: 'Run Windows apps on Mac without rebooting.' },
    { slug: 'camscanner', name: 'CamScanner Gold', category: 'productivity', color: '#1e88e5', blurb: 'Scan, OCR, and share documents from your phone.' },
    { slug: 'ilovepdf', name: 'iLovePDF Premium', category: 'productivity', color: '#e5322d', blurb: 'Merge, compress, convert, and edit PDFs in the browser.' },
    { slug: 'aiseesoft-recovery', name: 'Aiseesoft Data Recovery', category: 'productivity', color: '#2b6cb0', blurb: 'Recover deleted files from disks, USBs, and cards.' },
    { slug: 'malwarebytes', name: 'Malwarebytes Premium', category: 'antivirus', color: '#0d4f8b', blurb: 'Malware, ransomware, and web protection for Windows and Mac.' },
    { slug: 'mcafee-android', name: 'McAfee Mobile Security Android', category: 'antivirus', color: '#c01820', blurb: 'Antivirus, anti-theft, and Wi-Fi checks for Android phones.' },

    { slug: 'avg-secure-vpn', name: 'AVG Secure VPN', category: 'vpn', color: '#ff8000', recently: true, blurb: 'VPN from AVG for streaming, public Wi-Fi, and extra devices.' },
    { slug: 'moz-pro', name: 'Moz Pro', category: 'ai-tools', color: '#2d64ff', blurb: 'SEO rankings, keywords, and link research from Moz.' },
    { slug: 'ullu', name: 'Ullu', category: 'streaming', color: '#e11d48', blurb: 'Hindi web series and films. Ask which plan you need.' },
    { slug: 'vmware-workstation', name: 'VMware Workstation Pro', category: 'cloud', color: '#607078', recently: true, blurb: 'Run multiple VMs on a Windows or Linux PC.' },
    { slug: 'autocad', name: 'AutoCAD', category: 'graphics', color: '#0696d7', blurb: 'AutoCAD licence for drafting and 2D/3D design.' },
    { slug: 'windows-10-home', name: 'Windows 10 Home', category: 'microsoft', color: '#0078d4', blurb: 'Windows 10 Home licence for a single PC.' },
    { slug: 'windows-10-pro', name: 'Windows 10 Pro', category: 'microsoft', color: '#0078d4', blurb: 'Windows 10 Pro licence with Remote Desktop and BitLocker.' },
    { slug: 'windows-11-home', name: 'Windows 11 Home', category: 'microsoft', color: '#0078d4', blurb: 'Windows 11 Home licence for a single PC.' },
    { slug: 'windows-pro-mak', name: 'Windows Pro MAK 20 PC', category: 'microsoft', color: '#0078d4', blurb: 'Volume MAK key for up to 20 Windows 10/11 Pro PCs.' }

  ]
};

window.ANC_STORE.productCodes = {
  'titan-mail': 'TM Titan Mail',
  'google-meet': 'TM-KSN Google Meet',
  'microsoft-onedrive': 'TM-KSN-CM-KS OneDrive',
  'google-one': 'TM-KSN-CM-KS Google One',
  'zoom-pro': 'TM-KSN-KS Zoom',
  'stealth-writer': 'TM-KSN-CM Stealth Writer',
  'hix-ai-bypass': 'TM-KSN-CM HIX',
  'chatgpt-plus': 'TM-KSN-KS ChatGPT',
  'google-gemini-ai': 'TM-KSN-CM-KS Gemini',
  'paperpal-premium': 'TM-KSN-CM Paperpal',
  'jenni-ai': 'TM-KSN-CM Jenni',
  'ai-plagiarism-checker': 'TM Plagiarism',
  'scribd-premium': 'TM-KSN-CM-KS Scribd',
  'quillbot-premium': 'TM-KSN-KS Quillbot',
  'grammarly': 'TM-KSN Grammarly',
  'visio-professional': 'TM-CM Visio',
  'windows-11-pro': 'TM-KSN-CM-KS Win11',
  'microsoft-365-personal': 'TM-KSN-CM-KS 365 Personal',
  'windows-server': 'TM-KS Win Server',
  'microsoft-365-family': 'TM-KSN-CM-KS 365 Family',
  'office-windows': 'TM-KSN-CM-KS Office Win',
  'office-mac': 'TM-CM-KS Office Mac',
  'project-professional': 'TM-KSN-CM-KS Project',
  'office-365-account': 'TM-CM Office 365',
  'clipchamp': 'TM Clipchamp',
  'coreldraw': 'TM-KSN-CM CorelDRAW',
  'canva-pro-edu': 'TM Canva Edu',
  'canva-professional': 'TM-KSN-CM-KS Canva',
  'adobe-photography': 'TM-CM Adobe Photo',
  'capcut-pro': 'TM-KSN-CM CapCut',
  'envato-elements': 'TM-KSN-KS Envato',
  'adobe-creative-cloud': 'TM-KSN-CM Adobe CC',
  'kaspersky-vpn': 'TM-CM Kaspersky VPN',
  'surfshark-vpn': 'TM-KSN-KS Surfshark',
  'hma-vpn': 'TM-KSN-CM-KS HMA',
  'nordvpn': 'TM-KSN-KS NordVPN',
  'avast-vpn': 'TM-CM-KS Avast VPN',
  'express-vpn': 'TM-KSN-CM-KS ExpressVPN',
  'nitro-pdf-pro': 'TM-KSN Nitro',
  'notion': 'TM-KSN-CM Notion',
  'cleanmymac-x': 'TM-CM-KS CleanMyMac',
  'easeus-data-recovery': 'TM-CM-KS EaseUS',
  'ccleaner-professional': 'TM-CM CCleaner',
  'linkedin-premium': 'TM-KSN-CM Linkedin',
  'truecaller': 'TM-KSN-CM-KS Truecaller',
  'codedex-club': 'TM Codedex',
  'kids-worksheets': 'TM Worksheets',
  'datacamp': 'TM-CM DataCamp',
  'educative': 'TM-CM Educative',
  'skillshare': 'TM-KSN-KS Skillshare',
  'linkedin-learning': 'TM-CM Linkedin Learning',
  'udemy': 'TM-KSN-KS Udemy',
  'norton-security': 'TM Norton',
  'avg-internet-security': 'TM AVG',
  'eset-antivirus': 'TM ESET',
  'bitdefender-antivirus': 'TM Bitdefender',
  'mcafee-internet-security': 'TM-KSN-CM McAfee IS',
  'mcafee-total-protection': 'TM-KSN-CM McAfee Total',
  'mcafee-antivirus': 'TM-KSN-CM McAfee AV',
  'kaspersky': 'TM-KSN-CM Kaspersky',
  'speechelo-pro': 'TM-KSN Speechelo',
  'jetbrains-premium': 'TM-CM JetBrains',
  'dashlane': 'TM-CM Dashlane',
  '1password': 'TM 1Password',
  'roboform': 'TM-KS RoboForm',
  'github-student': 'TM-KSN-CM GitHub Student',
  'idm': 'TM-KSN-CM-KS IDM',
  'autodesk-apps': 'TM-CM-KS Autodesk',
  'icloud': 'KSN-CM-KS iCloud',
  'claude-ai': 'KSN-CM Claude',
  'grok': 'KSN-CM Grok',
  'perplexity-ai': 'KSN-CM Perplexity',
  'google-ai-ultra': 'KSN-CM Google Ultra',
  'midjourney': 'KSN Midjourney',
  'elevenlabs': 'KSN ElevenLabs',
  'replit-core': 'KSN Replit',
  'lovable-ai': 'KSN Lovable',
  'originality-ai': 'KSN Originality',
  'semrush': 'KSN-KS Semrush',
  'descript-ai': 'KSN Descript',
  'gamma-ai': 'KSN-CM Gamma',
  'devin-ai': 'KSN Devin',
  'suno-ai': 'KSN-KS Suno',
  'bolt-ai': 'KSN-CM Bolt',
  'heygen-ai': 'KSN-CM HeyGen',
  'invideo-ai': 'KSN-CM InVideo',
  'pollo-ai': 'KSN Pollo',
  'gptzero': 'KSN GPTZero',
  'turnitin': 'KSN Turnitin',
  'humanizeai-pro': 'KSN HumanizeAI',
  'humbot-ai': 'KSN Humbot',
  'figma': 'KSN-CM Figma',
  'beautiful-ai': 'KSN-CM Beautiful.ai',
  'freepik-premium': 'KSN-CM-KS Freepik',
  'adobe-premiere-pro': 'KSN Premiere',
  'filmora': 'KSN-CM-KS Filmora',
  'mcafee-mobile-vpn': 'KSN-CM McAfee VPN',
  'iscanner': 'KSN iScanner',
  'wps-office-pro': 'KSN-CM-KS WPS',
  'cursor-ai': 'KSN-CM Cursor',
  'coursera-plus': 'KSN-CM Coursera',
  'duolingo-super': 'KSN-CM Duolingo',
  'epidemic-sound': 'KSN-CM Epidemic',
  'mcafee-livesafe': 'KSN-CM LiveSafe',
  'netflix': 'KSN-CM-KS Netflix',
  'spotify-premium': 'KSN-CM-KS Spotify',
  'youtube-premium': 'KSN-CM YouTube',
  'prime-video': 'KSN-CM-KS Prime Video',
  'crunchyroll': 'KSN-CM-KS Crunchyroll',
  'sony-liv': 'KSN-KS SonyLIV',
  'zee5': 'KSN ZEE5',
  'google-workspace': 'CM Workspace',
  'google-workspace-education': 'ANC Workspace Edu',
  'digitalocean': 'CM DigitalOcean',
  'remote-desktop': 'CM Remote Desktop',
  'higgsfield': 'CM Higgsfield',
  'kling-ai': 'CM Kling',
  'github-copilot': 'CM Copilot',
  'microsoft-copilot': 'CM-KS MS Copilot',
  'writehuman': 'CM WriteHuman',
  'zerogpt': 'CM ZeroGPT',
  'german-exam': 'CM German Exam',
  'adobe-acrobat': 'CM Acrobat',
  'corel-videostudio': 'CM VideoStudio',
  'vmware-fusion': 'CM Fusion',
  'parallels-desktop': 'CM-KS Parallels',
  'camscanner': 'CM CamScanner',
  'ilovepdf': 'CM iLovePDF',
  'aiseesoft-recovery': 'CM-KS Aiseesoft',
  'malwarebytes': 'CM Malwarebytes',
  'mcafee-android': 'CM McAfee Android',
  'avg-secure-vpn': 'KS AVG VPN',
  'moz-pro': 'KS Moz',
  'ullu': 'KS Ullu',
  'vmware-workstation': 'KS Workstation',
  'autocad': 'KS AutoCAD',
  'windows-10-home': 'KS Win10 Home',
  'windows-10-pro': 'KS Win10 Pro',
  'windows-11-home': 'KS Win11 Home',
  'windows-pro-mak': 'KS Win MAK'
};

window.ANC_STORE.products.forEach((p) => {
  p.code = window.ANC_STORE.productCodes[p.slug] || ('TM ' + p.name);
});
